packages:
  - apps/*
  - packages/**/*
  - examples/**/*

catalog:
  '@effect/vitest': 0.27.0
  '@types/node': 24.10.4
  effect: 3.19.13
  hono: 4.11.3
  react: 19.2.3
  react-dom: 19.2.3
  react-router: 7.11.0
  react-router-dom: 7.11.0
  tsdown: 0.18.4
  typescript: 5.9.3
  zod: 4.2.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@seydx/node-av-darwin-arm64'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - node-av
  - nx
  - oxc-resolver
  - protobufjs
  - react-native-nitro-modules
  - sharp
  - unrs-resolver
  - workerd
